# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxufZXtWLj-qcsVY_r54APDQkSxRNCUS
"""

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

data = pd.DataFrame(iris.data, columns=iris.feature_names)

print("FIRST 5 ROWS OF DATASET")
print(data.head())

print("\nDATASET SHAPE")
print(data.shape)

print("\nCOLUMN NAMES")
print(data.columns)

print("\nSTATISTICAL SUMMARY")
print(data.describe())

print("\nMISSING VALUES")
print(data.isnull().sum())